### ISSUE TITLE
My Shifts profile link incorrect

### ISSUE THREAD

**Issue by natalieschauser** [brianmaissy/WSMA#12]
On the home page, select the “My Shifts” tab. If you then click on the profile tab, it will no longer bring you to the profile page (it returns you to the same my shift page.)

**Comment by rajatshah** [comment]
This also happens if you try to go via the shift allocation tab - at location http://107.20.135.212:8092/shifts

if I assign shifts and then click on the profile tab it just refreshes the page so I don't see the profile and I loose my assignments.

**Comment by brianmaissy** [comment]
This should be a simple fix; the profile link has no destination in the application.html.erb layout.
