### ISSUE TITLE
Create assignment link produces active record error if not logged in

### ISSUE THREAD

**Issue by natalieschauser** [brianmaissy/WSMA#13]
Without logging in, if you click on the “Create an Assignment” tab you get an Active Record :: RecordNotFound -- cannot find User without an ID.

**Comment by brianmaissy** [comment]
This is because the AssignmentsController needs a before_filter which calls authenticate. Tai, read the part of the design doc on authentication, or look at the UsersController for an example.

**Comment by taischuller** [comment]
I forgot to add the before_filters. I've added them to the controller and now it asks for login.
