### ISSUE TITLE
Create assignment link sometimes does not display anything

### ISSUE THREAD

**Issue by natalieschauser** [brianmaissy/WSMA#14]
I am logged in as admin. The link to the “Create an Assignment” brings me to this URL: http://107.20.135.212:8092/quickassign, but there is nothing on this page. 

(Just a note: I tried clicking on this url before and it only once showed me the correct assignment page, all other times it gave me this blank page. So sometimes it seems to work, but most of the time I get a blank page.)

**Comment by brianmaissy** [comment]
probably fixed with the detached server issue
