### ISSUE TITLE
New Chore Creation

### ISSUE THREAD

**Issue by Saami** [brianmaissy/WSMA#15]
I was logged in as an administrator and tried creating a new chore, but wasn't successful. I didn’t see it in the “Manage Shifts” section, or in the “Allocate Shifts” -- both logical places for the new chore to appear at. I would categorize this error as a blocker since creating a new chore is of immense importance.

**Comment by brianmaissy** [comment]
Did it appear on the right side of the "create chores and shifts" page?
You need to also create a shift based on that chore for it to appear in the shift management or allocation page.
