### ISSUE TITLE
Unable to go to Manage Shifts after attempting to create a chore

### ISSUE THREAD

**Issue by Saami** [brianmaissy/WSMA#18]
After attempting to create a new chore, I was directed to the following URL http://107.20.135.212:8092/chores, which didn't quite load. When i tried to navigate to manage shifts to see if the new chore had possibly appeared there, that page wouldn't load either, though it was trying to go to the following url http://107.20.135.212:8092/manageshifts. I will categorize this error as critical.

**Comment by brianmaissy** [comment]
persists even if you log out and log in as an admin (even though i tried creating a new chore as msw when the bug first appeared). --Saami

**Comment by brianmaissy** [comment]
restarting the server fixed this, for some reason. no idea what's causing it.

**Comment by brianmaissy** [comment]
fixed this by running server as detached. killing the terminal was messing it up.
