### ISSUE TITLE
Running the tests locally

### ISSUE THREAD

**Issue by rajatshah** [brianmaissy/WSMA#21]
Testing setup seems to be erroneous - running rake test yielded errors that related to setup of variables used in the controller.

**Comment by brianmaissy** [comment]
I don't think the testing setup is wrong, we know that three of the controllers have tests that are failing (ahem, get on that, frontend)

**Comment by rajatshah** [comment]
It may be the case that I tried to run the tests without setting it up on
the local machine properly, but I noticed that all the tests failed in the
last segment (108 tests failed) and the error involved a variable not being
assigned.

I can recreate the error and send you the output but I don't think this is
a critical problem so let me know if you want me to do that.

Thanks,

Rajat

On Mon, Nov 28, 2011 at 3:00 PM, Brian Maissy <
reply@reply.github.com

**Comment by brianmaissy** [comment]
Ah yeah, not that many should be failing. It could be an issue of ruby a gem version discrepancy. I wouldn't worry about it, but thanks.
