### ISSUE TITLE
Allocate shift, manage shift tabs on EC2 deployment code

### ISSUE THREAD

**Issue by rajatshah** [brianmaissy/WSMA#23]
tabs don’t work reliably 
when I'm signed in as admin - clicking the manage shifts tab links to an empty page

when signed in as wsm - Allocate shifts tab not always rendering the calendar used to allocate shifts.  

Whether I am logged in as admin or as wsm, if I create a chore and go back to the shift allocation page it does not render the calendar.

**Comment by rajatshah** [comment]
If I click on the allocate shifts tabs after having allocated shifts, the page refreshes and I loose the shifts I allocated earlier.

Also clicking manage shifts after allocating shifts renders a blank page in the deployment version.

In the local copy of the code, clicking manage shifts after allocation of shifts does not reflect the unassigned state of the chore in the manage shifts page.

I think the issue of discrepancy between the local code and the deployment code is important, but the more critical issue is the fact that it is not being reflected in the manage shifts page's calendar.

**Comment by brianmaissy** [comment]
It's possible that we fixed something since deploying to the ec2. We intentionally are not pushing all updates to it, because we don't want you guys to have to test an ever-changing application, that's not fair of us. So thanks for checking the edge code as well, but in general it's not your responsibility.

**Comment by brianmaissy** [comment]
Issues with blank shift management and chore creation pages fixed.
