### ISSUE TITLE
Colors and advancing time

### ISSUE THREAD

**Issue by rajatshah** [brianmaissy/WSMA#24]
I am not certain if the shift will turn red only if it is assigned and not completed by the deadline.

In either event, assuming shift allocation works, once I allocated the shift, the calendar event is still grey, and if I advance time past the due date, the shift does not turn red.

This issue is mild as it is a question of UI changes rather than framework.

As a suggestion, I think a submit button to allocate shifts would be useful, since it would notify the user as to when the shift allocation was successful.

**Comment by brianmaissy** [comment]
I don't know if the shift allocation page actually assigns the user to the shift. Cat?
